name: CI Pipeline

on:
  push:
    branches: ["**"] #Run on *any* branch
    paths-ignore: 
      -'**.md'
      - 'docs/**'
  pull_request:
    branches: ["**"] # 
    paths-ignore: 
      -'**.md'
      - 'docs/**'
  workflow_dispatch: #This line enables the "Run workflow" button  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          #strategy:
            #matrix:
              #node-version: [14, 16, 18] #add a matrix strategy to run tests in parallel
              node-version: 18 

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build the project
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './build'
          production-branch: 'main'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deployed from GitHub Actions 🚀'
        env:  
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          site-id: ${{ secrets.NETLIFY_SITE_ID }}
          

      
  deploy: 
    if: github.ref == 'refs/heads/main' #only deploys on main branch
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run build

      - name: Echo secret 
        run : echo "My secret is ${{secrets.DUMMY_SECRET}}"
        
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './build'
          production-branch: 'main'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deployed from GitHub Actions 🚀'
        env:  
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
